### ISSUE TITLE
Assertion failed: ([runtime isKindOfClass:[Mocha class]]), function Mocha_getProperty, file /<Path>/MochaRuntime.m, line 1016.

### ISSUE THREAD

**Issue by hxgqh** [matt-curtis/MochaJSDelegate#11]
Crash Report:

	Process:               Sketch [54881]
	Path:                  /Applications/Sketch.app/Contents/MacOS/Sketch
	Identifier:            com.bohemiancoding.sketch3
	Version:               43.1 (39012)
	Code Type:             X86-64 (Native)
	Parent Process:        ??? [1]
	Responsible:           Sketch [54881]
	User ID:               502

	Date/Time:             2017-10-07 17:19:37.031 +0800
	OS Version:            Mac OS X 10.12.4 (16E195)
	Report Version:        12
	Anonymous UUID:        E520C967-218C-D5E3-313F-F06CC791B541

	Sleep/Wake UUID:       ACE1A3A5-3BAA-4E6B-A901-AB87159498CF

	Time Awake Since Boot: 61000 seconds
	Time Since Wake:       13000 seconds

	System Integrity Protection: enabled

	Crashed Thread:        0  Dispatch queue: com.apple.main-thread

	Exception Type:        EXC_CRASH (SIGABRT)
	Exception Codes:       0x0000000000000000, 0x0000000000000000
	Exception Note:        EXC_CORPSE_NOTIFY

	Application Specific Information:
	Assertion failed: ([runtime isKindOfClass:[Mocha class]]), function Mocha_getProperty, file /Users/Shared/Jenkins/workspace/Staging/Modules/CocoaScript/src/framework/mocha/MochaRuntime.m, line 1016.

    426 com.apple.JavaScriptCore      	0x00007fffbd580728 llint_slow_path_get_from_scope + 1656
	427 com.apple.JavaScriptCore      	0x00007fffbd58672e llint_entry + 18432
	428 com.apple.JavaScriptCore      	0x00007fffbd581d4b vmEntryToJavaScript + 299
	429 com.apple.JavaScriptCore      	0x00007fffbd45cfde JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 158
	430 com.apple.JavaScriptCore      	0x00007fffbcc81d29 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 505
	431 com.apple.JavaScriptCore      	0x00007fffbd08c172 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 178
	432 com.apple.JavaScriptCore      	0x00007fffbcc81a14 JSObjectCallAsFunction + 788
	433 com.cocoascript.CocoaScript   	0x000000010707d6ad +[Mocha objectForJSValue:inContext:unboxObjects:] + 638
	434 com.cocoascript.CocoaScript   	0x000000010707af2f Mocha_getProperty + 109
	435 com.apple.JavaScriptCore      	0x00007fffbd4a1f4b JSC::JSCallbackObject<JSC::JSGlobalObject>::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) + 443
	436 com.apple.JavaScriptCore      	0x00007fffbd580728 llint_slow_path_get_from_scope + 1656
	437 com.apple.JavaScriptCore      	0x00007fffbd58672e llint_entry + 18432
	438 com.apple.JavaScriptCore      	0x00007fffbd581d4b vmEntryToJavaScript + 299
	439 com.apple.JavaScriptCore      	0x00007fffbd45cfde JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 158
	440 com.apple.JavaScriptCore      	0x00007fffbcc81d29 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 505
	441 com.apple.JavaScriptCore      	0x00007fffbd08c172 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 178
	442 com.apple.JavaScriptCore      	0x00007fffbcc81a14 JSObjectCallAsFunction + 788
	443 com.cocoascript.CocoaScript   	0x000000010707d6ad +[Mocha objectForJSValue:inContext:unboxObjects:] + 638
	444 com.cocoascript.CocoaScript   	0x000000010707af2f Mocha_getProperty + 109
	445 com.apple.JavaScriptCore      	0x00007fffbd4a1f4b JSC::JSCallbackObject<JSC::JSGlobalObject>::getOwnPropertySlot(JSC::JSObject*, JSC::ExecState*, JSC::PropertyName, JSC::PropertySlot&) + 443

**Comment by matt-curtis** [comment]
How are you using MochaJSDelegate that causes this error?

**Comment by matt-curtis** [comment]
Sounds like this isn't a MochaJSDelegate bug: http://sketchplugins.com/d/194-running-the-default-custom-plugin-causes-a-crash

Closing unless otherwise is indicated.
