### ISSUE TITLE
how would you call self or super methods in a function you set up

### ISSUE THREAD

**Issue by tarngerine** [matt-curtis/MochaJSDelegate#4]

**Comment by matt-curtis** [comment]
Well, for `self` (the current instance) you would simply do:

``` javascript
new MochaJSDelegate({ .. }).getClassInstance().callYourMethod()
```

`super` isn't really relevant, in this case, since `MochaJSDelegate` creates an `NSObject` subclass with new methods, it doesn't override/swizzle any. Mocha doesn't provide any built-in methods to replace existing method implementations.

**Comment by tarngerine** [comment]
like how would i call self in a handler i create when doing new MochaJSDelegate?

super relevant cuz remember i hacked this to do subclassing :p

``` javascript
 var cvItemPrototype = new MochaJSDelegate({
      "loadView:": (function() {
        [self setView:...] // how to do this?
      }),
      "setRepresentedObject:": (function(representedObject) {
         ...
      }),
  }, NSCollectionViewItem);
```

**Comment by matt-curtis** [comment]
Like this.

``` javascript
var cvItemPrototype = new MochaJSDelegate({

    "loadView:": (function(){
        cvItemPrototype.callYourMethod();
    }),

    "setRepresentedObject:": (function(representedObject){
        cvItemPrototype.callYourMethod();
    })

}, NSCollectionViewItem).getClassInstance();
```

**Comment by tarngerine** [comment]
nice! 

i know this isnt why this was written - but thanks  for your help. one more thing

how would you call [super someMethod]?

for example in sketch im drawing an NSMatrix, and I want to run some additional code on a mouseDown:

``` javascript
    var matrix = new MochaJSDelegate({
        "mouseDown:": (function(event) {
          [super mouseDown:event]; // not sure how to do this in mocha
          mouseDownHandler(matrix);
        })
    }, NSMatrix).getClassInstance();
```

if i dont call super here, then the normal behavior of mouseDown is gone (selecting a cell in the matrix)

**Comment by matt-curtis** [comment]
Huh, I'm a little surprised that works to override the method. Guess my understanding of `addMethod` needs some refining.

Anyway, you can't do what you want to do. There's no way to call the superclass implementation, Mocha's swizzling methods don't provide one.

**Comment by tarngerine** [comment]
thanks
