### ISSUE TITLE
setShouldKeepAround broken in 3.4

### ISSUE THREAD

**Issue by tarngerine** [matt-curtis/MochaJSDelegate#5]
sketch broke it so anything that you keep around, if you try to run something after the first run it'll not work

posting here bc i can't afford to wait for sketch to fix (They've said they'll fix in 3.4.1 but have not committed to a timeline). all the plugins we've built at fb have been down for 3 days. i know you've got tons of knowledge - do you know how to get around this issue? the issue seeeeems to be that the coscript is not being properly deallocated, and thereafter if you try to reference something like NSApplication.sharedApplication() on the 2nd run, it'll error out

demo file:
https://dl.dropboxusercontent.com/u/1650579/Test.sketchplugin.zip

run 1 and then 2, and watch console log

```
10/28/15 11:01:55.726 PM Sketch Beta[53344]: Exception: TypeError: NSApplication. class is not a function. (In 'NSApplication. sharedApplication()', 'NSApplication. sharedApplication' is 1.875320061373223e-306)
10/28/15 11:01:55.726 PM One (Sketch Plugin)[53344]: TypeError: NSApplication. class is not a function. (In 'NSApplication. sharedApplication()', 'NSApplication. sharedApplication' is 1.875320061373223e-306)
line: 331
sourceURL: /Users/tarng/Library/Containers/com.bohemiancoding.sketch3.beta/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Test.sketchplugin/Contents/Sketch/one.cocoascript
column: 27
```

**Comment by matt-curtis** [comment]
You're right, there's something weird going on with COScripts and how they're retained, it's very odd. I've been throwing things at this for awhile, and nothing works... :/ I'll let you know if I find anything, but whatever bug this is in their source seems like a breaking one.

**Comment by tarngerine** [comment]
Thanks. They said they've fixed it and are working on getting a beta out soon
