### ISSUE TITLE
Crash after `saveDocumentWithDelegate:didSaveSelector:contextInfo`

### ISSUE THREAD

**Issue by berkcebi** [matt-curtis/MochaJSDelegate#6]
Hey! I'm trying to get notified when the document is saved after calling `saveDocumentWithDelegate:didSaveSelector:contextInfo:` on the `doc`.

Here's what I've tried:

```
@import 'MochaJSDelegate.js'

COScript.currentCOScript().setShouldKeepAround_(true);

var delegate = new MochaJSDelegate({
    "document:didSave:contextInfo:": (function(document, didSave, contextInfo) {
        [NSApp displayDialog:"Done!" withTitle:"Awesome!"];

        COScript.currentCOScript().setShouldKeepAround_(false);
    })
});

[doc saveDocumentWithDelegate:delegate.getClassInstance() didSaveSelector:NSSelectorFromString(@"document:didSave:contextInfo:") contextInfo:nil];
```

This seems to crash on 3.4 though. Any ideas?

Thanks a lot! :beers:

**Comment by matt-curtis** [comment]
Can you check and see if this is issue #5? If so, upgrading to the latest version, 3.4.1 should fix it.

**Comment by berkcebi** [comment]
Thanks. Unfortunately it's the same on both 3.4.1 and 3.4.2 (Beta).

**Comment by matt-curtis** [comment]
So it has worked pre-3.4?

**Comment by berkcebi** [comment]
Don't know really, just gave this a try today. Sorry for the hassle.

**Comment by matt-curtis** [comment]
Huh, weird. I suspect it's either a threading or reference issue, not sure.

Why can't you use one of the synchronous `saveDocument:` variations?

**Comment by berkcebi** [comment]
I was just experimenting really. :) I'm going to stick with synchronous version I guess. Thanks!
