### ISSUE TITLE
What is the licensing for this?

### ISSUE THREAD

**Issue by tarngerine** [matt-curtis/MochaJSDelegate#7]
I'm thinking about open sourcing some of the things we've worked on at FB that depend on this amazling library — could you provide some licensing information in the readme so I can properly attribute? Thanks!

**Comment by matt-curtis** [comment]
Cool, will be awesome to see what you guys have come up with. [Done](https://github.com/matt-curtis/MochaJSDelegate/blob/master/LICENSE).

**Comment by tarngerine** [comment]
❤️

On Wed, Apr 6, 2016 at 8:50 AM -0700, "Matt Curtis" notifications@github.com wrote:

Closed #7.
